remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Akashdeep Singh
Description: Hands-on Networking Graduate focused on real-world solution and pratical problem solving
